### ISSUE TITLE
Rate limiting

### ISSUE THREAD

**Issue by NaamloosDT** [NaamloosDT/DSharpPlus#10]
I have to admit, the way I implemented rate limiting was cheap. I'm sorry for that. We still have to improve on it.

A few resources that are relevant:
https://github.com/hammerandchisel/discord-api-docs/issues/108
https://github.com/hammerandchisel/discord-api-docs/blob/master/docs/topics/Rate_Limits.md
Please comment with any other resources that could help developing rate limiting for DSharpPlus

- Naamloos

**Comment by nick-strohm** [comment]
Going to work on it tonight

**Comment by NaamloosDT** [comment]
More resources
https://github.com/hammerandchisel/discord-api-docs/commit/c4a4783fbacf69289f3841dedc9658b3016bc5fd

**Comment by NaamloosDT** [comment]
More rate limit info
https://github.com/hammerandchisel/discord-api-docs/blob/master/docs/topics/Rate_Limits.md (duh)

as you can see, every request also gives us some headers telling us how many requests we are able to make for that route, and the time it takes before it resets.

**Comment by NaamloosDT** [comment]
Implemented rate limiting. phew.. what a b*tch..
https://github.com/NaamloosDT/DSharpPlus/commit/588d2cc3bb219cf072e1cde7c8fda67e1b14f1a9
Please check if you guys agree on the way I did it.
If you guys agree, close this issue and read the bottom comment here: https://github.com/hammerandchisel/discord-api-docs/issues/108

**Comment by NaamloosDT** [comment]
No objections? well then I consider it fixed :D
