### ISSUE TITLE
Underscore in attachment name for embed causes 400

### ISSUE THREAD

**Issue by MandL27** [NaamloosDT/DSharpPlus#103]
I'm trying to use an attachment with an underscore in its filename in an embed. Every time I do so (either with `_` or `%5f`), I get a bad request (400) and the embed fails to send. Removing the underscore in the code and filename avoids the issue.

**Comment by NaamloosDT** [comment]
Weird, I don't see why this would cause an issue. I'll take a look at it once I return home. For now, just remove the underscores from file names.

**Comment by Emzi0767** [comment]
API restriction; invalid.

**Comment by NaamloosDT** [comment]
Ahh, did not know
