### ISSUE TITLE
Resuming a Connection

### ISSUE THREAD

**Issue by arcdigital** [NaamloosDT/DSharpPlus#107]
As mentioned at https://discordapp.com/developers/docs/topics/gateway, the gateway provides a session_id and each event streamed to the client has a sequence id. I have two questions:

1) If the client loses connection to the discord gateway and is able to reconnect automatically, does it automatically make a gateway resume call with the existing session id/last sequence id (and then process all the events replayed by the gateway).

2) If the client crashes, and it's restarted - when connecting is there a way to pass in the session_id and last received sequence id (assuming I'm logging this data somewhere else), so the gateway will replay all the missed events.

**Comment by Emzi0767** [comment]
I don't understand the purpose of this issue, but:

1. Yes
2. No

**Comment by Emzi0767** [comment]
On top of that I do not understand why would you open this issue in multiple repositories - that's plain spam.
