### ISSUE TITLE
On guild join event

### ISSUE THREAD

**Issue by johnfg10** [NaamloosDT/DSharpPlus#109]
Im not sure if i should be doing this in one of the existing events but i need to run some logic when the bot joins a guild(including at startup preferably) any suggestions?

**Comment by NaamloosDT** [comment]
Do it on guild join event

**Comment by johnfg10** [comment]
i cant seem to find any guildjoinevent https://dsharpplus.emzi0767.com/api/DSharpPlus.DiscordEventArgs.html

**Comment by Emzi0767** [comment]
`.GuildCreated`

**Comment by NaamloosDT** [comment]
https://dsharpplus.emzi0767.com/api/DSharpPlus.DiscordClient.html#DSharpPlus_DiscordClient_GuildCreated

**Comment by johnfg10** [comment]
ahh ok thank you
