### ISSUE TITLE
using Message.edit throws a error

### ISSUE THREAD

**Issue by johnfg10** [NaamloosDT/DSharpPlus#110]
https://gist.github.com/johnfg10/06b3e383f642d0f4c77a648ec7e258a2

**Comment by johnfg10** [comment]
seems to be happening with await msgArgs.Message.DeleteAsync(); too. the bot has full perms including administrator

**Comment by NaamloosDT** [comment]
Are you editing someone elses message? You can't do that.

**Comment by johnfg10** [comment]
oh you cant?

**Comment by Quahu** [comment]
Yes, you can't. That's what Naamloos just said.
