### ISSUE TITLE
Event user joins Channel

### ISSUE THREAD

**Issue by InfiniteCrazy** [NaamloosDT/DSharpPlus#111]
Hi,

I want the bot to do something when a user joins a channel, but I couldn't find a fitting event. Is there an event implemented and if not how can I solve it myself?

Thx for your help!

**Comment by Emzi0767** [comment]
You cannot join a text channel, and for voice channels there's `.VoiceStateUpdate`.

**Comment by InfiniteCrazy** [comment]
Thank you very much!
