### ISSUE TITLE
System.AggregateException in MESSAGE_CREATED

### ISSUE THREAD

**Issue by SubstituteCS** [NaamloosDT/DSharpPlus#113]
Consistent error when reading the values AvatarURL and Username (possibly other fields as well), when reading Author from a MessageCreatedEventArgs object.  
Even when checking that the value of Author isn't null, it seems as though these fields are.  
Creating a DiscordUser object and assigning it to the value of MessageCreatedEventArgs.Author first, then accessing the fields in DiscordUser works with no null issues.

**Comment by Emzi0767** [comment]
You should be able to do neither of these things, and author might be partial.

In addition to that, AggregateException literally means "one or more exceptions". Check the `InnerException`.

**Comment by SubstituteCS** [comment]
It's just null references all the way down.  
https://i.imgur.com/quTNb6y.png

**Comment by Emzi0767** [comment]
I checked. Latest version does not allow you to do that, and author should be set. Check your exception and report back with details.

**Comment by Emzi0767** [comment]
That still tells me nothing. This is not any more specific than AggregateException. I need stack trace.

**Comment by SubstituteCS** [comment]
https://i.imgur.com/F4Rfhly.png  
InnerException is null, the failing function is <Message>d__3.MoveNext()

**Comment by NaamloosDT** [comment]
would you mind building it under "debug" and running that build?

**Comment by Emzi0767** [comment]
`d__3.MoveNext()` is part of the allocated async state machine. I want full stack trace or I'll close this.

**Comment by NaamloosDT** [comment]
ouch naam. That^

**Comment by SubstituteCS** [comment]
That is the full stacktrace,  
https://i.imgur.com/vk6oSfH.png
@NaamloosDT Is being built under debug.

**Comment by SubstituteCS** [comment]
quoth.Author.IconUrl = message.Author.AvatarUrl;

**Comment by Emzi0767** [comment]
You need to initialize the Author on the embed before using it. Also 2.5.3 is outdated, latest is 2.5.4 (or 2.5.5-beta if using MyGet builds).

**Comment by NaamloosDT** [comment]
Was just going to say that :^)

**Comment by SubstituteCS** [comment]
Needed to clean solution, (for binaries), the sources were still the latest, I'll try initalizing the author object.

**Comment by SubstituteCS** [comment]
That fixed it, without documentation I assumed all the accessible properties were initialized on initalization of the object.

**Comment by Emzi0767** [comment]
They aren't. We'll also be releasing a simplified solution to constructing embeds in the future. For now, this is solved.
