### ISSUE TITLE
Invite.Accept is not working as it should

### ISSUE THREAD

**Issue by TrueLecter** [NaamloosDT/DSharpPlus#119]
```c#
var invite = await _discord.GetInviteByCodeAsync(inviteCode);
var serverID = invite.Guild.Id;
await invite.AcceptAsync();
```

This is what I've tried to do. There are no any error message, no exceptions as well as I'm still not joined by the invite. This is user account and invite code is 100% working.

Also, performing post request by myself works fine. 

Only difference between my request and library request - User-Agent header. When I add it to my request, request is successfully fulfilled  but user have not joined the guild. 

Is there any way to disable user agent?

**Comment by Emzi0767** [comment]
Currently this function unverifies and flags your account, in addition to not accepting the invite.

As this has only ever been used to facilitate building spam/raid bots, expect this function to be gone in a future version of the library.

**Comment by NaamloosDT** [comment]
I'm not too sure whether we should remove it though, I'm planning to add functionality for oauth2 apps and some oauth2 apps may want to use this

**Comment by Emzi0767** [comment]
I believe OAuth apps still cannot use that endpoint and require different means to add a user to a guild.
