### ISSUE TITLE
Connection attempt failed

### ISSUE THREAD

**Issue by SadEnergizer** [NaamloosDT/DSharpPlus#124]
Hey guys.
I use Win7 x64, VS2017, .Net Core 2.0, DSharpPlus 3.0, DSharpPlus.WebSocket.WebSocket4Net 3.0. Here is my code:
```
using System;
using System.Threading.Tasks;
using DSharpPlus;
using DSharpPlus.Net.WebSocket;

namespace ControlBot
{
    class Program
    {
        static DiscordClient discord;
        static void Main(string[] args)
        {
            MainAsync(args).ConfigureAwait(false).GetAwaiter().GetResult();
        }
        static async Task MainAsync(string[] args)
        {
            discord = new DiscordClient(new DiscordConfiguration
            {
                UseInternalLogHandler = true,
                LogLevel = LogLevel.Debug,
                AutoReconnect = true,
                Token = "mycorrecttoken",
                TokenType = TokenType.Bot
            });
            discord.SetWebSocketClient<WebSocket4NetClient>();

            discord.MessageCreated += async e =>
            {
                if (e.Message.Content.ToLower().StartsWith("ping"))
                    await e.Message.RespondAsync("pong");
            };

            await discord.ConnectAsync();

            await Task.Delay(-1);
        }
    }
}
```
I have an error like this: "Connection attempt failed, retrying is 7s". Where did I make an mistake?

**Comment by iDerp** [comment]
I'm pretty sure you don't setup the Discord Config there...
Like I have Program.cs with that (minus the Config code) and MyBot.cs where MyBot.cs has the config and event and other code.

**Comment by NaamloosDT** [comment]
He is setting up the discordconfig, it's a different issue @iDerp

**Comment by NaamloosDT** [comment]
@SadEnergizer don't use the websocket4net implementation. It's not intended for use with .net core

**Comment by NaamloosDT** [comment]
Hello? Opening an issue doesn't really work if you're not going to read our answers

**Comment by SadEnergizer** [comment]
Ok. I tried to run the app with .Net Framework 4.5.2, 4.6.2. The result was the same.

**Comment by NaamloosDT** [comment]
Try removing the configureawait part, it's unnecessary

**Comment by NaamloosDT** [comment]
`MainAsync(args).ConfigureAwait(false).GetAwaiter().GetResult();`
To
`MainAsync(args).GetAwaiter().GetResult();`

Other than that, everything should work fine

**Comment by NaamloosDT** [comment]
Also, wasn't .net core incompatible with win7?

For win7 you indeed need the websocket4net.. When you're using netfx

**Comment by SadEnergizer** [comment]
I don't know why, but it works now with my code above. Now I use .Net Framework 4.6.1. May be it was some problems with Discord server or my router. Who knows.

**Comment by NaamloosDT** [comment]
As long as it works c:

**Comment by SadEnergizer** [comment]
I think the reason was WebSocket4Net 0.15.0-beta9. I've just tested that version and stable version 0.14.1. Only the last is work.

**Comment by NaamloosDT** [comment]
You shouldn't update websocket4net, just download the dsharpplus websocket4net package.
