### ISSUE TITLE
Reaction ratelimit headers are wrong.

### ISSUE THREAD

**Issue by Emzi0767** [NaamloosDT/DSharpPlus#129]
As per https://github.com/hammerandchisel/discord-api-docs/issues/182 the reaction ratelimit headers send 1/1s, when in reality the limit is 1/0.25s.

We should decide whether we want to implement an override for this behaviour.

Pros:

- Faster reaction adding, as the limit is 4x higher than what discord says it is.

Cons:

- Potentially dangerous should the limit ever change, although it's not likely at the moment.

**Comment by NaamloosDT** [comment]
Seems like a plan to me

**Comment by NaamloosDT** [comment]
I mean, once rate limits for reactions get updated people would get errors soon enough and it'll be reported

**Comment by Emzi0767** [comment]
That... is a valid point. I'll consider all this.
