### ISSUE TITLE
Implement emoji endpoints

### ISSUE THREAD

**Issue by Emzi0767** [NaamloosDT/DSharpPlus#133]
As per https://github.com/hammerandchisel/discord-api-docs/pull/373, it looks like bots will now be able to control guild emojis.

**Comment by NaamloosDT** [comment]
Will implement tomorrow, if I get to it. Else this weekend.

**Comment by Emzi0767** [comment]
No, don't do that yet. Let's wait until they push them to docs.

**Comment by NaamloosDT** [comment]
It's not in yet? Will wait

**Comment by uwx** [comment]
this has been merged for a while now

**Comment by Emzi0767** [comment]
Where?

**Comment by uwx** [comment]
sorry, i meant the docs.
https://discordapp.com/developers/docs/resources/emoji

**Comment by Emzi0767** [comment]
@NaamloosDT it is time

**Comment by NaamloosDT** [comment]
Tomorrow c:

**Comment by knightking100** [comment]
@NaamloosDT Nice

**Comment by NaamloosDT** [comment]
"Tomorrow"

Sorry :'(
