### ISSUE TITLE
[BREAKING] Permission names

### ISSUE THREAD

**Issue by Emzi0767** [NaamloosDT/DSharpPlus#136]
Apparently **Read Messages** is now **Read Text Channels & See Voice Channels**.

![Proof](https://cdn.discordapp.com/attachments/106126169627181056/355646586878951434/Screenshot_from_2017-09-08_023211.png)

This means we need to rename `Permissions.ReadMessages` ([file link](https://github.com/NaamloosDT/DSharpPlus/blob/master/DSharpPlus/Enums/Permission.cs#L90)) to something else.

Some suggestions:

* `AccessChannel` or `AccessChannels` (sounds best IMO)
* `ViewChannel` or `ViewChannels`
* `SeeChannel` or `SeeChannels`

**Comment by NaamloosDT** [comment]
I agree on the first option
