### ISSUE TITLE
Ban events should use DiscordUser instead of DiscordMember

### ISSUE THREAD

**Issue by justcool393** [NaamloosDT/DSharpPlus#153]
Members that are banned are no longer members, which creates a "#0000" user in `GuildBanAddedEventArgs.Member` and `GuildBanRemovdEventArgs.Member`, making it impossible to retrieve the ban.

In addition, users are not required to be a member from a specific server in order to be banned.

**Comment by Emzi0767** [comment]
Prolly related to pulling the user from cache at all times. Or something else. Will have a look.

**Comment by Emzi0767** [comment]
Found the issue. Incorrectly deserialized JSON.
