### ISSUE TITLE
Not working with Windows 7

### ISSUE THREAD

**Issue by Discoli** [NaamloosDT/DSharpPlus#158]
Hey, I downloaded everything, set it all up, got the WebSocket4Net installed all in nuget but it still has a System.PLATFORMNOTSUPPORTED error for Windows 7.

How would I fix it because I have no choice but to use Windows 7 for this D:.
Ty!

**Comment by NaamloosDT** [comment]
Did you install the websocket4netcore or websocket4net package?

**Comment by Emzi0767** [comment]
This is a failure to follow instructions; re-read the docs, carefully this time

**Comment by Discoli** [comment]
```
This is a failure to follow instructions; re-read the docs, carefully this time
```

That was it, was just about to delete the issue, sorry for the unnecessary issue.

**Comment by Discoli** [comment]
Edit: Now it gives me this error
"Connection attempt failed, retrying in 7s"

but when I remove this line of code:             client.SetWebSocketClient<WebSocket4NetClient>();

it doesn't, welp.

```

        public static async Task MainAsync(string[] args)
        {
            client = new DiscordClient(new DiscordConfiguration
            {
                Token = TOKEN,
                TokenType = TokenType.Bot,
                UseInternalLogHandler = true,
                LogLevel = LogLevel.Debug
            });

            client.SetWebSocketClient<WebSocket4NetClient>();

            commands = DiscordClientExtensions.UseCommandsNext(client, new CommandsNextConfiguration
            {
                EnableMentionPrefix = true,
                StringPrefix = ".",
            });

            if (!File.Exists(Path.Combine(Path.GetTempPath(), CONNECT_FILE)))
            {
                client.GuildAvailable += Client_GuildAvailableAsync;
                File.WriteAllText(Path.Combine(Path.GetTempPath(), CONNECT_FILE), "");
            }

            commands.RegisterCommands<Commands>();
            await client.ConnectAsync();
            await Task.Delay(-1);
        }
```

**Comment by Emzi0767** [comment]
You are targeting .NETFX, this is a semi-known issue. You need to reinstall all of your NuGet packages. Sadly, this one is out of our control.

**Comment by Discoli** [comment]
Alright, No problem, will do it now, hopefully that'll solve it!

**Comment by Discoli** [comment]
https://i.imgur.com/D2DPFRL.png
Those are my packages, I uninstalled all of them then reinstalled them again, no luck.

Any other tips or should I try making a now project possibly?

**Comment by Emzi0767** [comment]
What FX are you targeting? 4.5?

Try uninstalling the packages and retargeting for 4.6 or 4.7.

**Comment by Discoli** [comment]
Yup, I was targetting 4.5, I'll try 4.6, 1 second.

**Comment by Emzi0767** [comment]
Remember to uninstall packages, retarget, then reinstall packages.

**Comment by Discoli** [comment]
Yea, uninstalled them all, retargetted and reinstalled, no avail.
I'll try creating a new project, see if that works.

**Comment by Emzi0767** [comment]
Did you update the WS4Net package? Because if you did, that's what's causing the problem.

**Comment by Discoli** [comment]
I didn't update it, I just installed the default.

This is the order I installed everything in and the versions, after launching after installing these still got the 7s disconnect 😭 

https://i.imgur.com/pfQJjxc.gifv

**Comment by NaamloosDT** [comment]
Did you do this? https://dsharpplus.emzi0767.com/api/DSharpPlus.DiscordClient.html#DSharpPlus_DiscordClient_SetWebSocketClient__1

**Comment by Discoli** [comment]
Re: NaamloosDT
I did that, once I remove it it works, but doesn't use the W4S thingy.

But once I set it to use the W4S thingy it gives me the 7s reconnect error message :\

**Comment by Emzi0767** [comment]
Could you try leaving it to reconnect? It will attempt 5 times, with exponential backoff, then rethrow whatever exception is causing it to stop.

**Comment by Discoli** [comment]
It seems to not keep reconnecting but just keeps being stuck here:
https://i.imgur.com/yGehEIM.png

**Comment by Emzi0767** [comment]
Yeah but after 5th attempt (ca. 3 minutes) it should give up and throw. I will need that exception.

**Comment by Discoli** [comment]
That seems to not be working for me, check out my code, maybe something is causing it:

https://hastebin.com/sinehuguri.cs

D:

I'll try adding a try catch incase an exception is being ignored.

**Comment by Discoli** [comment]
Fixed, was helped by @armaa on discord.

Use WebSocket4Net 
![kbgovpf](https://user-images.githubusercontent.com/29962520/30785200-bc8caa9a-a15a-11e7-9081-76278111627d.png)
0.14.1

woo!

**Comment by NaamloosDT** [comment]
🤦‍♂️

**Comment by Emzi0767** [comment]
So you did update packages after all, despite the fact that I explicitly told you not to.
