### ISSUE TITLE
DiscordMember.User relies on the user cache even when the User is specifically provided

### ISSUE THREAD

**Issue by uwx** [NaamloosDT/DSharpPlus#162]
this means DiscordMember.User and properties that reference it can't be accessed when the user cache is full, even when the DiscordMember object belongs to an event payload that specifically provides the User.

for example: **Guild Member Add** event's inner payload is a Member, and thus contains an User inside, but if the User Cache does not contain (due to it being full or perhaps it is not being added in time, which would be a relevant bug) a matching User object (which may or may not be outdated), GuildMember.IsBot will throw a KeyNotFoundException

if this, for some ungodly reason, is intended behaviour, i beg that at the very least a more relevant exception is thrown when the User cache does not contain the relevant User for that Member.

**Comment by Emzi0767** [comment]
When the user is proved, and not present in the cache, he's added to the cache.
