### ISSUE TITLE
Possible license violation

### ISSUE THREAD

**Issue by uwx** [NaamloosDT/DSharpPlus#179]
The D#+ license being a modified version of the DiscordSharp license appears to be in direct violation of the license itself; the clause that states the copyright notice must be included in all copies of the software implicitly states that it may not be included in a modified form, which it is.

Our license at its current state may provide a dangerous loophole that could allow some contributors to sue the project and have it taken down for illegally including code they retain ownership to.

A similar instance of this problem occurred to the Minecraft mod CraftBukkit in 2014.

I'm not sure how to approach this, opinions?

EDIT: We can get either an official contract signed by Mike explicitly doubly-licensing his existing code under the D#+ license as well as the original DiscordSharp license, or get a signature from everyone who's contributed more than 15 lines of code accepting the migration to the new license.
Or, we could just add the DiscordSharp license beside the D#+ license, with a note saying something like "Portions of this code are available under the following license." I'm not a lawyer, I have no idea.

**Comment by nick-strohm** [comment]
There is no code from DiscordSharp left. I initiated the rewrite. So i guess this isn‘t a problem.

**Comment by NaamloosDT** [comment]
I wanted to say this but couldn't find the words^

**Comment by Emzi0767** [comment]
Still, might be a good idea to include the original license.
