### ISSUE TITLE
Adding missing methods to various entities

### ISSUE THREAD

**Issue by Emzi0767** [NaamloosDT/DSharpPlus#181]
For most entities, certain missing methods should be added. Same methods should probably be moved from these entities' parent objects. An example would be `ModifyAsync()` and `.DeleteAsync()` for roles.

At the same time, it would be redundant to have the same methods on a guild. Similarly, methods that exist on both entities and parents should also deduplicated.

**Comment by NaamloosDT** [comment]
Didn't mean ta do that. thanks github.
