### ISSUE TITLE
cannot use default value for DiscordColor in async Task.

### ISSUE THREAD

**Issue by TheMorc** [NaamloosDT/DSharpPlus#182]
So the problem is in ` async Task <commandname>(CommandContext e,DiscordColor color = DiscordColor.Red) ` < there!
if i want to use ` DiscordColor color = DiscordColor.Red ` i am getting this error ` Default parameter value for 'color' must be a compile-time constant ` ..
Maybe i am doing something wrong...

**Comment by Quahu** [comment]
The issue you described is not related to the lib itself. It's how C# and structs work.

**Comment by TheMorc** [comment]
so what can be the fix for it?

**Comment by uwx** [comment]
You might be able to use `DiscordColor? colorHolder` and then inside the method
`var color = colorHolder ?? DiscordColor.Red;`
I'm not sure, depends how the library handles it.

**Comment by Emzi0767** [comment]
Library does not handle `Nullable<T>`. As pointed out, this is not a library problem, it's jow C# structs work. Best you can do is `default(DiscordColor)`.
