### ISSUE TITLE
UpdateRoleAsync strange(?) behaviour

### ISSUE THREAD

**Issue by armaa** [NaamloosDT/DSharpPlus#187]
I mean, its not strange, since i understand that permissions operate on bitwise flags, but then its impossible to put multiple permissions onto one role, unless you compare them with `|` operator..
I noticed, when you do `CreateRoleAsync` with just the name parameter, that it puts multiple permissions onto that role, in a way that it copies the permissions from the `@everyone` role. If its possible with this, wouldnt it be possible to do it with `UpdateRoleAsync` as well, in a way to check already placed/existing flags on the role and combine them with the one sent inside the method? That way, the method name would make more sense, since this works like `DiscordMember.ReplaceRolesAsync`

inb4 clickbait title

**Comment by moonPtr** [comment]
clickbait title

**Comment by Emzi0767** [comment]
I don't see how that behaviour would be confusing. Permissions are bit flags, and that's how they work. Updating permissions is as easy as `role.Permissions | new_permissions` to add, and `role.Permissions & ~deny` to remove.

**Comment by armaa** [comment]
Well, when you `Update` something, it means that the previous behaviour/settings/whatever stay the same and you just add the new thing on top of that

**Comment by Emzi0767** [comment]
Not really. Update means partial replacement of object's properties.

At any rate, this is how Discord API works, so it's also how the library works.

**Comment by armaa** [comment]
Thats also true.. Would it be possible to create a method that operates in a way described above? Is it even possible to get the already set permissions for the role in the library?

**Comment by Emzi0767** [comment]
See https://github.com/NaamloosDT/DSharpPlus/issues/187#issuecomment-335772012

**Comment by armaa** [comment]
Understandable then. Have a nice day 👍
