### ISSUE TITLE
Gateway stream compression

### ISSUE THREAD

**Issue by Emzi0767** [NaamloosDT/DSharpPlus#189]
As of today (2017-10-13) gateway supports stream compression via zlib by specifying `compress=zlib-stream` via query string when connecting. This compresses the entire WS stream.

As per discussion in DAPI devs, the zlib context is to be reused (meaning we might need a stream-less zlib implementation). This also requires potentially major changes to all WS client implementations.

Furthermore, the compression settings in Discord client instance will most likely be an enum (`CompressionLevel`) with 3 values now: `None`, `Payload`, and `Stream`.

**Comment by armaa** [comment]
Whats the actual difference between `Payload` and `Stream`?

**Comment by Emzi0767** [comment]
Level at which compression is applied.
