### ISSUE TITLE
Implement webhook-only client

### ISSUE THREAD

**Issue by Emzi0767** [NaamloosDT/DSharpPlus#190]
This came up previously (Naam's idea), and as of 6915db4d9eca002870d8cceb0e5b7db611a49286 (with the fix from f0530e026b0c4455b438cfa5b3f6f92b6bdce0c9) it is possible to implement a meta-client that can be used for the purposes of executing webhooks only.

A meta-client would be a simple class that does not inherit from `BaseDiscordClient`, and only uses a `DiscordApiClient` to perform specific REST actions.

This would allow integrating DSharpPlus into applications that only use Discord to post messages.

**Comment by uwx** [comment]
Do webhooks have rate limits?

**Comment by Emzi0767** [comment]
Yes. The webhook ID is also considered a major route parameter as of recently.

**Comment by armaa** [comment]
So if i understood correctly, you could 'act' as a normal user through the hook and do whatever the REST allows you to do?

**Comment by uwx** [comment]
Indeed.

**Comment by armaa** [comment]
Interesting.. Sounds a bit like how you could execute bot commands on non-bot flagged account and talk normally on it too

**Comment by Emzi0767** [comment]
The webhook client would be only for executing webhooks. What you hook that up to is entirely up to you. Webhooks only allow posting messages.

**Comment by NaamloosDT** [comment]
got em
