### ISSUE TITLE
VoiceNextConnection.<SendAsync> will throw an InvalidOperationException after about a minute of playing.

### ISSUE THREAD

**Issue by Kriste00** [NaamloosDT/DSharpPlus#192]
# Summary
An `InvalidOperationException` occurs at `VoiceNextConnection.<SendAsync>` after playing for 30 - 180 seconds. This happens randomly every time i start a song.

# Details
OS: `Win 10`
D#+ `Version: 3.0.0 - 4.0.0`
Framework: `.NET Core 2.0 (x64)`
Binaries: `ibopus (x64)
libsodium (x64)`

Stacktrace
```
System.InvalidOperationException: The connection is not initialized
   at DSharpPlus.VoiceNext.VoiceNextConnection.<SendAsync>d__157.MoveNext()
```

# Steps to reproduce
1. Set up vnext
2. Connect to a channel
3. Start playing a song
4. Will throw an `InvalidOperationException` after about a minute.

# Notes
I have been havind this problem since DSP 3.0.0 and have heard others having the same problem but no solution. :(

**Comment by moonPtr** [comment]
Switch to x86 binaries and and compile as x86/"Any CPU", see if that works out for you

**Comment by Kriste00** [comment]
With the x86 it dident work at all.

**Comment by moonPtr** [comment]
Strange. Are you using Debug or Release mode?

**Comment by Kriste00** [comment]
Debug

**Comment by Kriste00** [comment]
Debug

**Comment by Kriste00** [comment]
It makes a difference?

**Comment by moonPtr** [comment]
Yes. Where are you connecting / playing audio from? From a command or a from an event handler?

**Comment by moonPtr** [comment]
Bizarre, this seems different from the "usual problems"
Hang in there!

**Comment by Kriste00** [comment]
But does voice work for u?

**Comment by Emzi0767** [comment]
It's a known issue, I'll be investigating that when I get to voice parts of the 4.0 plan.

**Comment by Kriste00** [comment]
Ok

**Comment by Emzi0767** [comment]
I believe this is now resolved.
