### ISSUE TITLE
VoiceNextClient.ConnectAsync never returns

### ISSUE THREAD

**Issue by exelix11** [NaamloosDT/DSharpPlus#194]
I'm trying to make a bot join a voice channel, but when i call vnext.ConnectAsync from a command it never returns but i can see in the voice channel the bot actually joined, so i tryed playing some audio but vnc.SendAsync never returns as well.
Both my code and the example code don't work.

All libraries from nuget: version 3.2.2
.NETFX 4.6.1 
Windows 10 Fall creators update
Default WebSocket client
Visual Studio 2017
No exception.

To reproduce: 
```
[Command("join")]
        public async Task Join(CommandContext ctx)
        {
            var vnext = ctx.Client.GetVoiceNextClient();
            var vnc = vnext.GetConnection(ctx.Guild);
            var chn = ctx.Member?.VoiceState?.Channel;
            vnc = await vnext.ConnectAsync(chn);
            await ctx.RespondAsync("Connected");
        }
```
The answer is never sent, but in discord the bot is shown in the voice channel.

**Comment by Emzi0767** [comment]
This is failure to follow instructions; re-read the docs, particularly the [setup section](https://dsharpplus.emzi0767.com/articles/vnext_setup.html).

**Comment by exelix11** [comment]
Yep i'm sorry i forgot to copy the dlls from release to debug.
Thanks

**Comment by GorkyR** [comment]
I DID download the appropiate opus + sodium .dll's. (I tried both x64 and x86 anyway)
I DID copy them to the output folder, next to the .exe. (And I noticed log output includes "[VoiceNext]" logs when I do, so I'm guessing they are being noticed.)
Yet, I have exactly the same problem, with the exact same behaviour, with a similar setup:
  .NETFX 4.7.2
  DSharpPlus 3.2.3
  Visual Studio 2019
  Windows 10
Similarly no exceptions either, whether I include the .dll's or not. 

Are the instructions out of date, or am I missing something?

**Comment by F1restar4** [comment]
In 3.2.3 the voice binaries still had their lib prefixes (so libsodium and libopus) IIRC
or you should just update to 4.x

Also two year issue necro

**Comment by extremecodetv** [comment]
Same problem, method ConnectAsync never returns result

specs:
```
.NET Core 3.0.100
D#+ 3.2.3
VS2019
Windows 10 1903
```

I tried sodium and opus x64 libraries from dsharp website
https://dsharpplus.emzi0767.com/natives/index.html

and latests versions from official websites of libs

![image](https://user-images.githubusercontent.com/16631907/72750898-b4384d80-3bf0-11ea-8b24-b4ccaf4881e7.png)

**Comment by Kiritsu** [comment]
Try using version 4.0 of the lib

**Comment by BetaAngel** [comment]
Same problem, I've tried both 64x and 32x, ConnectASync never returns and I get no errors, I've tried publishing it, I've tried debug and release, I've tried putting the .dlls in the root, and the exe directory. My bot will join, but never returns. I'm using the libs provided on the page
- .NETCore 3.1
- D#+ v4.0.0-nightly-00669
- VS2019
- Windows 10 64x

**Comment by Kiritsu** [comment]
Can you show your bot's folder with the dlls inside it please?

**Comment by BetaAngel** [comment]
![image](https://user-images.githubusercontent.com/39318697/77128581-01853f80-6a27-11ea-9e3b-1f86ea5564ff.png)

**Comment by Kiritsu** [comment]
Since you're using v4 of the lib, remove `lib` prefixes on both sodium and opus dlls.

**Comment by BetaAngel** [comment]
Alright, but it still doesn't seem to be returning anything

**Comment by Kiritsu** [comment]
Welp. I just tried on the 4.0 examples project (that you can find here: https://github.com/Kiritsu/DSharpPlus-Examples-4.0).

I filled `config.json` file with my bot token, copy/pasted `opus.dll` and `sodium.dll` (https://dsharpplus.emzi0767.com/natives/vnext_natives_win32_x64.zip) and also put `ffmpeg.exe` (https://dsharpplus.emzi0767.com/natives/ffmpeg_win32_x64.zip) in the same folder then ran in debug mode in VS and seems to be working just fine.

Can you try to reproduce the issue on that project? (`DSPlus.Examples.CSharp.Ex04`)

**Comment by BetaAngel** [comment]
Sure on it right now, (i'll edit this message with any info)

**Comment by Kiritsu** [comment]
I updated the repo to the latest version and fixed build issues.

How to use:
![Image](https://storage.alnmrc.com/6e7c5bf69e954f548385245f6838c00f.png)

How your output folder looks like:
![Image](https://storage.alnmrc.com/362e0e1bb255442d980862241934c73d.png)

**Comment by BetaAngel** [comment]
Well it works fine now, I don't know what I did wrong on my project.

**Comment by Kiritsu** [comment]
Do you have some code you could provide?

**Comment by BetaAngel** [comment]
![image](https://user-images.githubusercontent.com/39318697/77129479-8756ba00-6a2a-11ea-9248-7ddae77f9a84.png)
     
```
public async Task RunAsync(string token, string ID, string masterID, string vers)
        {
            Token = token;
            UserID = masterID;
            CurrID = ID;
            StartTime = Process.GetCurrentProcess().StartTime;
            Version = vers;
            var config = new DiscordConfiguration()
            {
                AutoReconnect = true,
                LogLevel = LogLevel.Debug,
                TokenType = TokenType.Bot,
                MessageCacheSize = 2048,
                Token = Token,
                UseInternalLogHandler = true,
            };

            client = new DiscordClient(config);
            
            client.Ready += OnClientReady;
            client.MessageDeleted += OnMessageDeletion;
            client.MessageUpdated += OnMessageUpdate;
            client.MessageReactionAdded += OnReactionAdded;
            client.MessageReactionRemoved += OnReactionRemoved;
            client.GuildMemberAdded += OnGuildMemberAdded;
            client.GuildMemberRemoved += OnGuildMemberRemoved;
            client.ChannelCreated += OnChannelCreated;
            client.ChannelDeleted += OnChannelDeleted;
            client.ChannelUpdated += OnChannelEdit;

            string[] prefixes = new string[1];
            prefixes[0] = "m!";
            var commandsConfig = new CommandsNextConfiguration
            {
                EnableMentionPrefix = true,
                CaseSensitive = false,
                EnableDms = false,
                StringPrefixes = prefixes,
                IgnoreExtraArguments = true
                
            };
            client.UseInteractivity(new InteractivityConfiguration
            {
                
            });



            commands = client.UseCommandsNext(commandsConfig);

            commands.RegisterCommands<DebugCommands>();
            commands.RegisterCommands<Starboard>();
            commands.RegisterCommands<Admin>();
            commands.RegisterCommands<Audio>();

            client.GetVoiceNext();
            voice = client.UseVoiceNext();

            await client.ConnectAsync();

            
            await Task.Delay(-1);


        }
```

**Comment by Emzi0767** [comment]
First: x64 and x86, there's no 64x or 32x, and Windows doesn't come in x32.

Second, inspect exceptions.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Kiritsu** [comment]
It's fixed already.

**Comment by brilletjuh** [comment]
I'm not so sure it is fixed.
I am still having this same problem.
The bot connects, Discord shows the bot as connected, but ConnectAsync never returns.
If i remove the async, it returns, but when disconnecting or playing sound, D#+ reports it as not actually connected.

I used the exact code from the manual, changing only the command names and some variable names.

.NETFX 4.7.2
Windows 10 1909 x64
D#+ 3.2.3
VS 2019 latest update
Default websocket client

**Comment by Kiritsu** [comment]
Use nightly versions.

**Comment by brilletjuh** [comment]
Honestly, I rather sick with this version.
I would expect the stable version (3.2.3) to be stable and working, I don't want to rely on nightly builds.
I hop that is not the only way to get this thing working...

Oddly enough, the testbot included in the repo does work properly.

After doing some digging, I found that I do receive the OP2 code (line 833 in VoiceNextConnection.cs), the heartbeats are working, but an endpoint is never discovered (line 750).

**Comment by uwx** [comment]
The test bot uses the nightly version.

**Comment by Emzi0767** [comment]
Voice Gateway v1 was obsoleted, and might already be out of commision. 3.2 does not support any newer version. Only 4.x implement the v2 and v3 protocol required for voice to work properly.

**Comment by brilletjuh** [comment]
Emzi0767, Thank you, that is an actual explanation. In that case I'll have to use the nightly versions.
Do you have any idea when 4.x will come to NuGet?

**Comment by Emzi0767** [comment]
When it's ready

**Comment by Sombody101** [comment]
> Use nightly versions.

Where would I get the nightly version?

**Comment by OoLunar** [comment]
Latest nuget pre-release

**Comment by Sombody101** [comment]
I have it installed, but nothing has changed.
Am I missing something?

**Comment by OoLunar** [comment]
Feel free to join our Discord or create a Github Discussion for more support: https://discord.gg/dsharpplus

**Comment by JMcConahie** [comment]
I had this same issue with the latest version and came across this thread. After struggling for a long time, I fixed by running my application as Admin. Hope this helps someone else.
