### ISSUE TITLE
Suggestion: Make DefaultHelp supply full command name to help formatter

### ISSUE THREAD

**Issue by moonPtr** [NaamloosDT/DSharpPlus#195]
Simply adding a .WithQualifiedCommandName() (or .WithFullCommandName()) method to IHelpFormatter and adjusting DefaultHelpAsync accordingly would do the trick.

**Comment by moonPtr** [comment]
On a side note, it also doesn't allow for (completely) safe detection of groups. Like sure, `(if name != null &% subcommands != null) || groupExecutable`, it's probably a group, but what about groups with no subcommands that aren't executable on their own? Sounds pretty dumb, but consider a hidden group with hidden commands. If the override for .WithSubcommands() filters out hidden commands, it may appear as if the group is empty.

As a solution I'd suggest replacing .WithGroupExecutable() with something along the lines of .IsCommandGroup(bool groupExecutable)
Sure it breaks with the .WithX() naming, but so does .Build() :p

**Comment by Emzi0767** [comment]
Except `Build()` is a standard fluent builder thing, as is `WithX`. `Is`, not really.

**Comment by moonPtr** [comment]
Would `AsCommandGroup()` work?

**Comment by Emzi0767** [comment]
Help interface has been reworked as of 5afb0800374df1da65fc6ae43f0aae291f68a12a.
