### ISSUE TITLE
[Suggestion] CNext: Respond with string for Task<string> Commands

### ISSUE THREAD

**Issue by NaamloosDT** [NaamloosDT/DSharpPlus#200]
# Summary
Just a suggestion: Make Task<string> respond with the string returned. I don't want to touch cnext and get sniped by emzi for breaking that (it's Emziware)

# Details
```cs
[Command("reply")]
public async Task<string> ReplyAsync(CommandContext ctx)
{
    return "Hello World!";
}
```
and the bot should respond with `Hello World!`

# Notes
I don't want to get killed by Emzi for touching cnext or adding stuff to CNext without discussing

**Comment by uwx** [comment]
would be nice to have support for returning DiscordEmbed as well

**Comment by NaamloosDT** [comment]
+1 to that

**Comment by NaamloosDT** [comment]
or even returning a (string, DiscordEmbed) combo but i'm not sure whether that'd work for all of the frameworks we're targeting

**Comment by uwx** [comment]
^^ ValueTuple is NETFX 4.7 only, but there is [a NuGet package](https://www.nuget.org/packages/System.ValueTuple/) for compatibility. Not sure if it's worth the overhead.

**Comment by NaamloosDT** [comment]
Probably not, though (partly) porting it to the lib might be a possibility too

https://github.com/dotnet/corefx/blob/master/src/System.ValueTuple/src/System/ValueTuple/ValueTuple.cs

**Comment by Emzi0767** [comment]
This is one of the things I considered and rejected early on. Adds unnecessary complexity. If anything, I'd use the return types to perhaps indicate a condition other than success, but even then, added complexity for no gain at all.

**Comment by NaamloosDT** [comment]
:c

**Comment by Emzi0767** [comment]
There's also the performance aspect. This would cause a significant performance hit to command registration code, possibly command invocation code, and with coming changes to CNext, it'd make the whole CNext codebase extremely hard to debug, test, and maintain.
