### ISSUE TITLE
Request: [Hidden] attribute for command arguments to hide them from IHelpFormatter

### ISSUE THREAD

**Issue by uwx** [NaamloosDT/DSharpPlus#202]
Currently the `[Hidden]` attribute cannot be used on a command's arguments. It would be nice to have this feature implemented, with the attribute hiding the argument from IHelpFormatter help message.

**Comment by Emzi0767** [comment]
That... doesn't really make sense?

**Comment by uwx** [comment]
well thats what everyone keeps saying. i would find it useful in an edge case like [the ModCore reminder parser](https://github.com/NaamloosDT/ModCore/blob/e6d1a8a1a67769af3844789fb9b33b9ca8e5221c/ModCore/Commands/Reminders.cs#L65) where the command argument being present adds no useful information.

**Comment by Emzi0767** [comment]
To be honest, that's just one edge case. You can roll your help formatter which just conditionally ignores that argument.

**Comment by uwx** [comment]
alright, that settles this one then.

**Comment by Emzi0767** [comment]
Also I'm going to redesign that interface a bit, so it's a little bit more... hacking-friendly? I guess. The idea is to pass it more data in a better form (i.e. a whole `Command` object rather than disjointed properties).

**Comment by moonPtr** [comment]
While we're at it, can we make the HiddenAttribute applicable to types, analog to how applying an ExecutionCheck to a type applies it to all commands within that type?
