### ISSUE TITLE
Tagging a non-group class with the Hidden attribute doesn't add the check to the commands.

### ISSUE THREAD

**Issue by GHXX** [NaamloosDT/DSharpPlus#203]
# Summary
When you add commands to a class that is not tagged as a command group (doesn't have the Group attribute) and you add the Hidden attribute to it, then 'command.IsHidden' is FALSE for every command that doesn't have the Hidden attribute set manually (add it to every method/command).

Adding it to every method (command) in the class is a valid workaround. But the RequireOwner Attribute is added as a pre-execution check for the command. For all the methods/commands in the class.

# Example
```
namespace MyBestBotYet
{
    [Hidden, RequireOwner]
    class OwnerCommands
    {
        [Command("shutdown"), Aliases("exit")]
        public async Task Shutdown(CommandContext ctx) // this command takes no arguments
        {
                //some super cool code
        }

        [Command("say"),Hidden]
        public async Task Say(CommandContext ctx, [RemainingText, Description("What the bot will say.")] string sayStr)
        {
                 //some even cooler code
        }
}  
```
In the example above the 'say' command will be hidden, but the shutdown command will NOT.
Both commands however will be OwnerOnly.

# Note
This issue was found during playing with the custom help formatter provided by emzi. The following line showed the issue. where toplevel is an IEnumerable of commands. IsHidden will be true for 'say' and false for 'shutdown'
...
var sxs = toplevel.Where(xc => !xc.IsHidden);
...
Command object during runtime: 
http://prntscr.com/hdwen1

**Comment by moonPtr** [comment]
That's what I keep asking for lmao

**Comment by NaamloosDT** [comment]
as far as I know, this is intended. When that class is used as a group, the group will be hidden from help but its subcommands won't be.

Though that's my opinion on that matter. CNext is emziware so he'll be the one to decide.

**Comment by uwx** [comment]
then you should be able to do `Hidden(children: true)` to hide including children

**Comment by NaamloosDT** [comment]
Good point 😅

**Comment by GHXX** [comment]
#makeithappen 😆

**Comment by Emzi0767** [comment]
Checks are inherited, other attributes are not. Iunno, I'll think about it.
