### ISSUE TITLE
Separate functions for getmessages 

### ISSUE THREAD

**Issue by NaamloosDT** [NaamloosDT/DSharpPlus#206]
# Summary
GetMessages should be split up into three methods

# Details
GetMessages has three optional arguments that default to 0, which basically change the behavior of the request. These requests should be split up into three methods for GetMessagesBefore, After and Around. 

I'll take care of this myself, just making sure I'll remember

**Comment by Emzi0767** [comment]
Maybe rather than splitting they should get the same treatment as #201 i.e. new aliases rather than replacement. Otherwise I agree.

**Comment by NaamloosDT** [comment]
Possibly, though it just doesn't make sense to me to have three optional arguments of which no more or no less then one should be given

**Comment by Emzi0767** [comment]
That does make sense I suppose.

**Comment by NaamloosDT** [comment]
Yeah, I just thought it would be better to have methods that don't have any optional arguments when possible
