### ISSUE TITLE
Message updated events will sometimes duplicate

### ISSUE THREAD

**Issue by uwx** [NaamloosDT/DSharpPlus#211]
# Summary
The MessageUpdated events will sometimes duplicate. The second event will contain a `null` Message.

# Details
.NETFX 4.6.1 / Windows 10
Same bug in both 3.2.3 and 4.0.0 nightly.

# Steps to reproduce
1. Create MessageUpdated event listener
69. Edit message
420. Things go wrong

# Notes
Will attempt repro soon pls wait kthx

**Comment by NaamloosDT** [comment]
Can't we like, just like, *not* fire the event if the message object is null?

**Comment by uwx** [comment]
I'm guessing it's a little more complicated than that underneath.

**Comment by NaamloosDT** [comment]
like, just do an if statement

oh right of course it is :^)

**Comment by Emzi0767** [comment]
What message contents were you putting in the message?

**Comment by uwx** [comment]
nevermind i can't reproduce
