### ISSUE TITLE
CommandsNext dependency resolver

### ISSUE THREAD

**Issue by disshishkov** [NaamloosDT/DSharpPlus#214]
Add an ability to use an existing dependency resolver instead of custom, passed to commands configuration class.

**Comment by Emzi0767** [comment]
As of 4.0, we use Microsoft's Dependency Injection.

**Comment by disshishkov** [comment]
any details?

**Comment by Emzi0767** [comment]
If you're using [nightly builds](https://dsharpplus.emzi0767.com/articles/nightly.html), we use MSDI. This is not yet included in the official documentation, but a partial documentation is available [in the repo itself](https://github.com/NaamloosDT/DSharpPlus/blob/master/docs/articles/commands/dependency_injection.md).

Note that nightly builds are a breaking change when coming from 3.2, and, as the API is not yet finalized for 4.0 release, things will be changing a lot. This doesn't mean that 4.0 builds are unstable, but things might occasionally break.
