### ISSUE TITLE
Request: New discord status (watching and listening)

### ISSUE THREAD

**Issue by nathan130200** [NaamloosDT/DSharpPlus#218]
Add discord listening and watching status for bots.

**Comment by Emzi0767** [comment]
That's implemented in 4.0. Currently there are no plans to release 3.3.

**Comment by nathan130200** [comment]
You aren't D#+ Developer.

**Comment by Emzi0767** [comment]
I'm the most active maintainer, and the one that implemented this in 4.0. 3.x is on feature freeze unless we decide to release 3.3.

**Comment by moonPtr** [comment]
"You aren't D#+ Developer." 
![image](https://user-images.githubusercontent.com/32428601/34382400-e3091214-eb0e-11e7-83e8-e192501f195c.png)

Boi

**Comment by li223** [comment]
Ofc. Those were clearly faked.

**Comment by NaamloosDT** [comment]
That's implemented in 4.0. Currently there are no plans to release 3.3.

**Comment by armaa** [comment]
![1367924801338](https://user-images.githubusercontent.com/5805051/34383296-a5d086e2-eb14-11e7-9d47-1a31add346f0.jpg)

**Comment by NaamloosDT** [comment]
![Imgur](https://i.imgur.com/rUsKYCY.png)

**Comment by nathan130200** [comment]
@Emzi0767 Collaborator != Project Owner.

**Comment by uwx** [comment]
![](https://i.imgur.com/kdt77vf.jpg)

**Comment by nathan130200** [comment]
@uwx i don't asked nothing for you, don't intrudes where it is not called.

**Comment by uwx** [comment]
![](https://i.imgur.com/pQO7CJZ.jpg)

**Comment by WamWooWam** [comment]
I mean, emzi's a bit more than a "collaborator" at this point, and anyway, why would you need *specifically* the project owner?

**Comment by nathan130200** [comment]
Lot of fanboy defeding him. 😂 😂 😂 😂 😂 i hate you foreigners.

**Comment by uwx** [comment]
![](https://i.imgur.com/34CrMMr.png)

**Comment by Emzi0767** [comment]
This isn't a place for shitposting.

**Comment by NaamloosDT** [comment]
![sorry](https://saiko.is-a-good-waifu.com/278fa9.png)
