### ISSUE TITLE
Old Emojis / New Missing

### ISSUE THREAD

**Issue by HurricanKai** [NaamloosDT/DSharpPlus#224]
# Summary
The Problem is, that an DiscordEmoji parameter takes in strings and converts them without them beeing an Emoji / isnt converting real emojis
I put both issues together, cause its the same part that has to be changed i assume

# Details
I Dont think much is needed here, besides the Emojis:

Missing:
- "duck"
- "deer"
- "potato"

Outdated:
- "car"

(all phrases with ":" in front and back)

# Steps to reproduce
1. Create Command with DiscordEmoji parameter
2. Try it with those above

# Notes
I will add any more i find, and when ive got time, ill check all Emojis if they are missing.
I cannot check all possible phrases for Outdated, but as i find some...

**Comment by Giggitybyte** [comment]
Found another missing one: `octagonal_sign`
