### ISSUE TITLE
Impossible to instantiate the DiscordOverwrite class

### ISSUE THREAD

**Issue by Quahu** [NaamloosDT/DSharpPlus#230]
Make sure you familiarize yourself with our contributing guidelines.

# Summary
Can't create a channel with permission overwrites because the constructor is internal.

# Details
Can't create a channel with permission overwrites because the constructor is internal and not public.

# Steps to reproduce
1. Try to create a channel with overwrites without having any overwrites

# Notes
my first issue

**Comment by Emzi0767** [comment]
> my first issue

I will be gentle

**Comment by li223** [comment]
You're this gentle with me. :(

**Comment by uwx** [comment]
It would probably make sense for there to be a DiscordOverwriteBuilder, so you can do something like
`guild.CreateOverwrite(member OR role).Grant(permission).Deny(permission).Build()`

**Comment by Emzi0767** [comment]
Yes, I was thinking of taking an approach like this.

**Comment by NaamloosDT** [comment]
something something bcca136
