### ISSUE TITLE
RegexOptions.Compiled breaks .NET Core.

### ISSUE THREAD

**Issue by Emzi0767** [NaamloosDT/DSharpPlus#236]
# Summary
.NET Core 1.x appears to lack support for `RegexOptions.Compiled`.

# Details
It just :b:reaks. Microsoft lied to me. To all of us.

# Steps to reproduce
1. Use CNext in a .NET Core 1.x project.
2. Watch the thing crash because of unexpected regex options.

# Notes
Should prolly bump the minimum target for compiled regex to Standard 2.0 and FX only.

**Comment by NaamloosDT** [comment]
Mike you fuck why did you lie
