### ISSUE TITLE
InternalGetMessages can't get more than 50 messages

### ISSUE THREAD

**Issue by NaamloosDT** [NaamloosDT/DSharpPlus#27]
GET request don't support payloads (.NET), though it has to for Discord's API. The Get Channel Messages endpoint requires a payload with a message ID and a limit. Neither of these can be filled in as .NET doesn't support this. We have two possible solutions.
1) Keep it like this, limited to only the 50 latest messages
2) 3rd party library for webrequests

So, what are we going to do? Any other suggestions?

**Comment by nick-strohm** [comment]
There is no payload in GET requests. It says query params in the api documentation and not json params. Already changed it. Pushing it soon

**Comment by NaamloosDT** [comment]
great, my fault
