### ISSUE TITLE
Crashes when you delete a role

### ISSUE THREAD

**Issue by SpiderWebb2002** [NaamloosDT/DSharpPlus#29]
So, while the bot was on, i tried to delete a role. 
![image](https://cloud.githubusercontent.com/assets/7851653/22662327/e1a1b50c-ec3b-11e6-9e62-277fc15e8a77.png)

**Comment by NaamloosDT** [comment]
fixed in https://github.com/NaamloosDT/DSharpPlus/commit/54169809291e4325ba94c9cbb94f40275b7dc60c
