### ISSUE TITLE
Still crashing in private

### ISSUE THREAD

**Issue by SpiderWebb2002** [NaamloosDT/DSharpPlus#31]
![untitled](https://cloud.githubusercontent.com/assets/7851653/22663516/3837518e-ec40-11e6-8365-7c2e7c08972c.png)

**Comment by NaamloosDT** [comment]
Answered in Discord PM :)
![image](https://cloud.githubusercontent.com/assets/12187179/22663669/bed73386-ecad-11e6-85d0-11378f22af77.png)
