### ISSUE TITLE
[Suggestion] Send embed using client.SendMessage()

### ISSUE THREAD

**Issue by KingDGrizzle** [NaamloosDT/DSharpPlus#32]
Currently, I think the only way to send an embed is (DiscordClient is client in this example)

`e.Channel.SendMessage("", false, embed)`.

Maybe we can get `client.SendMessage(e.Channel.ID, "", false, embed)`?

**Comment by NaamloosDT** [comment]
Updated in https://github.com/NaamloosDT/DSharpPlus/commit/b52020feb37f23e321af682732c72722bc64793f
