### ISSUE TITLE
NullRefException using Commands

### ISSUE THREAD

**Issue by Zilounay** [NaamloosDT/DSharpPlus#40]
Hey man,

Been using your lib for a bit now but I can't get my head around an issue I'm having when following your tutorials. I think they might be out of date or maybe there is a bug.

```
DiscordClient _client = new DiscordClient(new DiscordConfig()
{
       Token = "qsdfqsdf.qsdf.qsdf",
       AutoReconnect = true
});

_client.MessageCreated += async (e) =>
{
    if (!e.Message.Author.IsBot)
    {
          if (e.Message.Content.StartsWith("!hello"))
          await e.Channel.SendMessage($"Hello, {e.Message.Author.Username}");
     }
};

var c = new CommandConfig
{
    Prefix = "!",
    SelfBot = false
};

_client.UseCommands(c);

_client.AddCommand("hello", async (e) =>
{
      await e.Message.Parent.SendMessage($"Hello, {e.Message.Author.Mention}");
});

_client.Connect();
Console.ReadLine();
```

I get the following exception : 
`{"Method not found: 'DSharpPlus.DiscordMessage DSharpPlus.MessageCreateEventArgs.get_Message()'."}`	
`System.MissingMethodException`

And it happens as soon as a message is sent (not specifically with the prefix, just any message).

I'm guessing I'm just using the lib like a retard but I couldn't find a working scenario, could you possibly send some love to make it work ? :D 

Thanks man

**Comment by NaamloosDT** [comment]
Try replacing `e.Message.Parent.SendMessage` with `e.Message.Reply`? tell me if that fixes anything?

**Comment by Zilounay** [comment]
.Reply doesn't exist on Message

**Comment by NaamloosDT** [comment]
Excuse me, `.Respond`

**Comment by Zilounay** [comment]
Nope does not fix, same steps to reproduce

**Comment by NaamloosDT** [comment]
There doesn't seem to be anything wrong. Could you send me the full exception data?

**Comment by Emzi0767** [comment]
It would be wise to remove that token from your code, and regenerate it on your app's page.

Also it appears you might be using an outdated version of DSharpPlus with up-to-date version of Command Module or vice-versa. Where did you get either from? Latest version of the Command module relies on `EventArgs` parameters being properties, this is not yet available on NuGet. If that is the case (and it looks like it is), you need to compile DSharpPlus from the repository.

**Comment by Zilounay** [comment]
I got DSharpPlus from the nuget and Command from building this repo, is that okay?

**Comment by Emzi0767** [comment]
Nope. Nuget has not yet been updated with `EventArgs` changes.

**Comment by Zilounay** [comment]
okay i'll update and contact you later on if needed :) got some SC2 ladder going on right now :l

**Comment by NaamloosDT** [comment]
Good luck! I'll go back to playing mk8 ;)

**Comment by Zilounay** [comment]
Yep this was the issue. using the repo's .dll instead of nuget makes it work.
Thanks a lot guys, and great work so far !
