### ISSUE TITLE
Trying to use a User Token to connect

### ISSUE THREAD

**Issue by BoySanic** [NaamloosDT/DSharpPlus#45]
![image](https://cloud.githubusercontent.com/assets/26152620/25066655/8dc7cfbc-21fa-11e7-8a74-f65121c02825.png)

**Comment by NaamloosDT** [comment]
This probably has something to do with events being slightly different for user tokens. I'm not quite sure what causes this issue.
Though we don't plan on supporting user tokens atm, as bot tokens still need a lot of work.
