### ISSUE TITLE
DiscordClient.cs InternalModifyGuidRole

### ISSUE THREAD

**Issue by spyro76** [NaamloosDT/DSharpPlus#47]
May have found a typo in the InternalModifyGuildRole method in DiscordClient.cs.
Looks like a missing "/", didn't look into whether this should be fixed on the line (2459 in github) or somewhere else.

Current:  string url = Utils.GetAPIBaseUri() + Endpoints.Guilds + "/" + guild_id + Endpoints.Roles + role_id;
Fixed:  string url = Utils.GetAPIBaseUri() + Endpoints.Guilds + "/" + guild_id + Endpoints.Roles + "/" + role_id;

**Comment by Emzi0767** [comment]
Fixed as of [this commit](https://github.com/NaamloosDT/DSharpPlus/commit/5066734f38c1db374b43c260815d7fa46ec599f3).
