### ISSUE TITLE
DiscordRole.Position doesnt work

### ISSUE THREAD

**Issue by Jarmmo** [NaamloosDT/DSharpPlus#50]
DiscordRole.Position doesnt update when doing Guild.UpdateRole, Emzi0767 said that it's not implemented yet

**Comment by Emzi0767** [comment]
Should be fixed now. Please confirm and I'll close the issue.

**Comment by Emzi0767** [comment]
Commenting here so I remember:

* Add guild modify position method to guild and client, since that how it's done.

**Comment by Emzi0767** [comment]
2.1.6-rc fixes this, hopefully.

**Comment by Emzi0767** [comment]
Fixed in 2.1.7-rc.
