### ISSUE TITLE
Using current master on Windows 7 (fast fix)

### ISSUE THREAD

**Issue by bodziowolf** [NaamloosDT/DSharpPlus#52]
Hey. I've come up with a quick solution to work with your library on Windows 7 on master branch and would like to share. How would like it to be contributed? Patch? Pull request? My weird idea is to currently maintain master-websocket4net branch and update it with master branch from time to time. Not super convenient, but that's what I'm currently using right now :)

Cheers!

**Comment by Emzi0767** [comment]
2.0.0-rc has a WS4Net provider, and can be used under Windows 7 (both via .NET Core and .NETFX). Code on master branch is being slowly obsoleted in favour of code on netcore branch. If you want to submit a PR, feel free to do so, however I'd prefer if the WS4Net code was provided as an alternative to the default one, rather than a replacement.

**Comment by bodziowolf** [comment]
netcore requires windows 10 creators update as it requires .net 4.7.0 package  :D 

2.0.0-rc corresponds to master or different branch? Maybe its possible for me to use it instead.

**Comment by Emzi0767** [comment]
2.0.0-rc is the netcore branch, and it only requires .NETFX 4.7 to build (that was also disabled recently, until AppVeyor gets support for thereof, for now it just caps of at .NETFX 4.6.2). You can run it on .NETFX 4.5.2+, .NET Core 1.0+, and any other platform targeting .NET Standard 1.1+ (such as Xamarin, Universal Windows Platform, Windows 8 Metro, Windows Phone 8).

If you want to use 2.0.0, you want to do so via NuGet or MyGet. Check pre-release in your NuGet window, and install `DSharpPlus`. If you want to use the WS4Net or WS# provider, install `DSharpPlus.WebSocket.WebSocket4Net` or `DSharpPlus.WebSocket.WebSocketSharp` respectively. The former is preferred, as it is more stable.

To use the MyGet feed (which generally contains more recent builds), add `https://www.myget.org/F/dsharpplus-nightly/api/v3/index.json` to your NuGet sources first.

**Comment by bodziowolf** [comment]
Installing NuGet prerelase + WebSocket4Net solved my trouble as well :)

I also see that WebSocket4Net and WebSocketSharp do not support .netcore, I'll try to tinker with this when I have some time.

**Comment by Emzi0767** [comment]
They don't, because the underlying libraries do not support .NET Standard.

**Comment by Emzi0767** [comment]
I'll close that for now, comment if you have further questions.

**Comment by bodziowolf** [comment]
They don't, because the underlying libraries do not support .NET Standard.

Yeah, WebSocket4Net has some .netcore support only in beta package, but that might not be stable yet.

**Comment by Emzi0767** [comment]
Problem is, these are pre-release packages. I would prefer not to rely on pre-release packages in the project, because that forces marking your project as pre-release as well. In case we go out of pre-release earlier than those packages, it will present a problem.

**Comment by bodziowolf** [comment]
Indeed, that would be my thoughts as well.
