### ISSUE TITLE
DiscordClient.UpdateStatus() not working

### ISSUE THREAD

**Issue by SulkyG** [NaamloosDT/DSharpPlus#53]
Hi!

I'm getting a `System.NullReferenceException` when I'm using `_client.UpdateStatus("!help");`

Any idea why?

Thank you.

**Comment by Emzi0767** [comment]
At a glance that's probably because your client is null. I would need to see more to tell.

**Comment by NaamloosDT** [comment]
Hello there! Try setting your client status in the Ready event. Please tell me whether this changes anything :)

**Comment by NaamloosDT** [comment]
I'm closing this issue because we haven't been able to reproduce the issue, also because you're not answering anymore.
