### ISSUE TITLE
DiscordEmbedThumbnail does not allow http

### ISSUE THREAD

**Issue by OmniKahedron** [NaamloosDT/DSharpPlus#54]
Official Discord docs say "source url of the thumbnail (only supports http(s) and attachments)"
https://discordapp.com/developers/docs/resources/channel#embed-thumbnail-structure

Yet, when using an http url, Discord will not display the image (it does work with other libraries, as seen here https://cdn.discordapp.com/attachments/146044397861994496/310709387318788096/unknown.png )

**Comment by NaamloosDT** [comment]
Were you using the exact same image url? for both tests?

**Comment by OmniKahedron** [comment]
Yes, same website, same image url. Only difference is that the person in the screenshot is using a different library (Discord.py afaik)

**Comment by NaamloosDT** [comment]
that's... interesting. I'll check it out later
