### ISSUE TITLE
Bot is duplicating Messages

### ISSUE THREAD

**Issue by Craftplacer** [NaamloosDT/DSharpPlus#55]
If my Bot starts at all; I write a test message but it´s getting duplicated. _(and then is going to crash.)_

![image](https://cloud.githubusercontent.com/assets/22963120/25869774/daf06316-3501-11e7-952c-8c359646bdf8.png)

**Comment by NaamloosDT** [comment]
Wait that's not supposed to happen.. Care to send me your code via Discord?

**Comment by Craftplacer** [comment]
while loop is not good.

**Comment by NaamloosDT** [comment]
Uhh

**Comment by OmniKahedron** [comment]
no u

**Comment by Craftplacer** [comment]
DO YOU SEE THAT THE ISSUE IS CLOSED?

**Comment by Jarmmo** [comment]
haha yes

**Comment by Craftplacer** [comment]
If I would be Naamloos I would delete it RIGHT NOW!

**Comment by OmniKahedron** [comment]
no u

**Comment by Craftplacer** [comment]
could you just shut up?

**Comment by NaamloosDT** [comment]
no u

**Comment by Craftplacer** [comment]
no u

**Comment by OmniKahedron** [comment]
no u

**Comment by OmniKahedron** [comment]
no u
(we're gonna get banned for this)

**Comment by Craftplacer** [comment]
no u

**Comment by OmniKahedron** [comment]
no u

**Comment by Craftplacer** [comment]
no u

**Comment by OmniKahedron** [comment]
no u

**Comment by Craftplacer** [comment]
no u

**Comment by OmniKahedron** [comment]
no u

**Comment by Craftplacer** [comment]
no u

**Comment by OmniKahedron** [comment]
no u

**Comment by Craftplacer** [comment]
no u

**Comment by NaamloosDT** [comment]
It's been enough

**Comment by NaamloosDT** [comment]
Stop
