### ISSUE TITLE
CommandContext.Guild.Roles is null

### ISSUE THREAD

**Issue by OmniKahedron** [NaamloosDT/DSharpPlus#56]
Was trying to make a command that lists a server's roles, but accessing ctx.Guild.Roles always throws a NullReferenceException... (EnableDms is false)

**Comment by Emzi0767** [comment]
Known issue; will be fixed soon-ish. This is related to our de-staticizing, there's still some leftovers that cause problems.

**Comment by Emzi0767** [comment]
I reworked large part of the cache initialization code. This should be fixed when I push the commits tomorrow.

**Comment by NaamloosDT** [comment]
Pin and unlimited are implemented AFAIK, just the update event is missing

**Comment by Emzi0767** [comment]
@NaamloosDT I think this is the wrong issue.

At any rate, this should be fixed now, as per latest updates to cache initialization. If it isn't, I'll re-open the issue.

**Comment by NaamloosDT** [comment]
Was at animecon & not really awake lol
