### ISSUE TITLE
InteractivityExtension.Split missing end

### ISSUE THREAD

**Issue by Rohansi** [NaamloosDT/DSharpPlus#58]
`InteractivityExtension.Split` cuts off the end of text. I replaced it with this and it works for me.
```cs
public static IEnumerable<string> Split(this string str, int chunkSize)
{
    var len = str.Length;
    var i = 0;

    while (i < len)
    {
        var size = Math.Min(len - i, chunkSize);
        yield return str.Substring(i, size);
        i += size;
    }
}
```

**Comment by NaamloosDT** [comment]
Thank you very much. I'll test it and if it works implement it. (the sudden splitting was my mistake, as i was unable to find out a different way to do this)

**Comment by NaamloosDT** [comment]
Thank you very much. I have implemented this and am about to push it soon.
