### ISSUE TITLE
Missing bounds checks in SendPaginatedMessage navigation

### ISSUE THREAD

**Issue by Rohansi** [NaamloosDT/DSharpPlus#59]
`SendPaginatedMessage` page navigation doesn't clamp the `CurrentIndex` value so it can go out of bounds and start throwing exceptions.

**Comment by NaamloosDT** [comment]
There's bounds checks actually. Check [This](https://github.com/NaamloosDT/DSharpPlus/blob/netcore/DSharpPlus.Interactivity/InteractivityModule.cs#L440). Reopen if i'm wrong.
