### ISSUE TITLE
SendPaginatedMessage evaluates the IEnumerable multiple times

### ISSUE THREAD

**Issue by Rohansi** [NaamloosDT/DSharpPlus#62]
This can be bad for performance depending on what the actual type is. It could be a LINQ query and in that case the query will run every time something like `First()`, `Count()`, or `ToArray()` is used.

Should just eagerly `ToList()` at the start of the method and use that instead.

**Comment by NaamloosDT** [comment]
Should be fixed in next commit. Please reopen if i'm wrong
