### ISSUE TITLE
"Could not find channel last message belonged to" Exception

### ISSUE THREAD

**Issue by kef95** [NaamloosDT/DSharpPlus#67]
It's not just for one message but for every single message that the server sends, and for all the channels. I did not try kicking and rejoining the bot unfortunately.

**Comment by Emzi0767** [comment]
This is related to joining guilds and how GUILD_CREATE is handled as a result.

**Comment by Emzi0767** [comment]
Unable to reproduce, this might be related to an older version.

Will re-open if more data is supplied.

**Comment by Emzi0767** [comment]
I managed to accidentally reproduce it.

**Comment by Emzi0767** [comment]
So after a bit of investigation, root cause seems to be Discord itself. In other words nothing we can easily or reliably fix.
