### ISSUE TITLE
[Suggestion]GetMessagesAsync

### ISSUE THREAD

**Issue by GHXX** [NaamloosDT/DSharpPlus#72]
could we have the ability to get all messages since a certain date in a discord channel? i think that would be amazing.
Thanks in advance

**Comment by OmniKahedron** [comment]
Discord search esque stuff in general would be neat, though you could probably code that in yourself
might write a class for that tomorrow, too lazy rn

**Comment by Emzi0767** [comment]
Discord search is not available to bots yet. I'm closing this, at least until it becomes available.

For now, you can loop `.GetMessagesAsync()` until you find ones that no longer meet your criteria.
