### ISSUE TITLE
Gateway v6

### ISSUE THREAD

**Issue by Emzi0767** [NaamloosDT/DSharpPlus#75]
Currently, we support only Gateway v5. Specifying v6 in client config introduces some subtle problems.

What should be done:

- [x] Remove the gateway version switch - introduces problems and doesn't actually help
- [ ] Properly implement GWv6

All work should happen on a new branch.

**Comment by NaamloosDT** [comment]
Gateway v6 isn't officially released yet though..

**Comment by Emzi0767** [comment]
Technically, it is. Still, this is something to investigate.

**Comment by Emzi0767** [comment]
@Rapptz gave me this: https://github.com/Rapptz/discord.py/commit/ddd3fd0a3dcce2d48b2df26377e136f2310809b3

It should help.

**Comment by Emzi0767** [comment]
Basics are implemented. Remaining features are to be considered:

* Call messages https://github.com/Rapptz/discord.py/commit/bd39c3ef458e7b78e1e4d49367544a04ab764131 
* System message types (group DM only) https://github.com/Rapptz/discord.py/commit/a128249b6324dd045561cb0be85cdabf8acd7694
* Better handling for group DM channel updates https://github.com/Rapptz/discord.py/commit/69c506d7aeb9f1a0a6f711b7b8c144f8b554b0d7

**Comment by Emzi0767** [comment]
Closing for now.
