### ISSUE TITLE
Update example bots

### ISSUE THREAD

**Issue by Emzi0767** [NaamloosDT/DSharpPlus#78]
The currently-existing example bots were written for 1.x. As many things have changed between 1.x and 2.x, these example bots should be updated to reflect these changes.

- [x] Update @Emzi0767's example bot
- [x] Update @NaamloosDT's example bot

**Comment by NaamloosDT** [comment]
I'll be onto it later today ;)

**Comment by NaamloosDT** [comment]
Mine has been updated. Closing this issue.
