### ISSUE TITLE
Joining new guilds doesn't properly update the cache

### ISSUE THREAD

**Issue by Emzi0767** [NaamloosDT/DSharpPlus#79]
Guild cache is not properly updated when a bot joins a guild.

This should be updated for 2.2.x.

**Comment by Emzi0767** [comment]
Once upon a time, there was a bug. Whenever someone tried to investigate it, it stopped manifesting itself. I'll leave this open, because this is becoming annoying.

**Comment by Emzi0767** [comment]
...I didn't meant to close it.

**Comment by NaamloosDT** [comment]
What parts do not get updated properly?

**Comment by Emzi0767** [comment]
The guild cache appears to not reflect joining guild, although it's extremely random.

**Comment by Emzi0767** [comment]
Since no one complained as of last changes, I am closing this.
