### ISSUE TITLE
Not all message-based events try to return the message.

### ISSUE THREAD

**Issue by Emzi0767** [NaamloosDT/DSharpPlus#84]
Certain message events return a skeleton message. This should be fixed.

**Comment by Emzi0767** [comment]
No complaints; closing.

**Comment by uwx** [comment]
message skeleton is still returned when the message isn't in the cache, rather than it being automatically fetched by the id. you might want to mark as 'wontfix' if this is intentional.

**Comment by Emzi0767** [comment]
It is indeed.

**Comment by uwx** [comment]
maybe you could add a flag to DiscordMessage to reliably check if message body present or if it's just the skeleton.
