### ISSUE TITLE
Check user role

### ISSUE THREAD

**Issue by LeaderSoul** [NaamloosDT/DSharpPlus#87]
Hello
I don't know where can I get help about this, so I write here.
How can I check if the xyz user has ADMIN rank/role?

**Comment by Emzi0767** [comment]
At the very least, you can try checking permissions for a channel, provided you have a user.

**Comment by NaamloosDT** [comment]
It also kinda depends on *how* you want to achieve this, do you want to check by role name? by role ID? by permission?

**Comment by LeaderSoul** [comment]
Ok, I know now. I used the examples. :) I found today this DSharpPlus and it is very good. :) Better than Discord.net :D Before I used discord.net but there is many missing function which I need. So thank you @NaamloosDT . :D You saved my life. :D
