### ISSUE TITLE
CommandNext have no permission

### ISSUE THREAD

**Issue by LeaderSoul** [NaamloosDT/DSharpPlus#88]
Hello
I use this: https://github.com/Emzi0767/DSharpPlus-Example-Bot and mostly DSPlus.Examples.CSharp.Ex02 part. I modified the code and I thought I screwed up, so I use now the default example source.
But I get this message with both:
`[2017-06-27 01:07:14 +02:00] [ExampleBot] [Error] TestAdmin tried executing 'admin' but it errored: DSharpPlus.CommandsNext.Exceptions.ChecksFailedException: One or more execution pre-checks failed.`

And I get this message in Discord:

> Access denied
> :no_entry: You do not have the permissions required to execute this command.
> 

I tried use the command so: !admin nick Test TestChange

So the Test user's nickname will change to TestChange. 
My prefix is **!** .
I gave to my account all permissions.
What is the problem?

**Comment by Emzi0767** [comment]
It might be related to a permission bug in 2.2. I believe this is fixed in the 2.3 branch, which means that the fix will be going live with that version. Shouldn't be long. I'll confirm it though.

**Comment by LeaderSoul** [comment]
I found what is the problem. Hmm it seems I must select all permissions for bot otherwise I get above messages.
Before I selected only Manage Nicknames in Discord Roles settings because in code is there: Permissions.ManageNicknames

So I thought that it is ok if I choose only Manage Nicknames.
