### ISSUE TITLE
RespondWithFileAsync(string file_path) causes an error.

### ISSUE THREAD

**Issue by SubstituteCS** [NaamloosDT/DSharpPlus#90]
[Line that invokes the exception](https://cdn.discordapp.com/attachments/222524756920893441/335246530137292801/unknown.png)
Exception Text
> Exception thrown: 'System.Net.Http.HttpRequestException' in mscorlib.dll ("Error while copying content to a stream.")  

Issue starts on line 232 of DiscordMessage.  Passing my own FileStream into RespondWithFileAsync works just fine.

**Comment by EarsKilla** [comment]
i think it because `Position` field of file stream not set to `0` before send here:
https://github.com/NaamloosDT/DSharpPlus/blob/master/DSharpPlus/DiscordRestClient.cs#L356

but i no have time now to fork, fix (maybe), test

**Comment by Emzi0767** [comment]
I'd need to see the exact code.

**Comment by Emzi0767** [comment]
Also the stream position is purposely not set to 0. You are expected to rewind the stream yourself.

**Comment by Emzi0767** [comment]
This is fixed with e7e5bde.
