### ISSUE TITLE
Groups case sensitive

### ISSUE THREAD

**Issue by wantedghost** [NaamloosDT/DSharpPlus#99]
There's an exception thrown: System.InvalidOperationException: Sequence contains no matching element

In this case:
 [Group("Countries")]
(...)
   [Command("Get")]

If I call <prefix> countries get, it will throw the exception, but if I call <prefix> countries Get, it will be okay. I think there's a problem when checking the commands.

**Comment by Emzi0767** [comment]
I see the problem. Will fix later.

**Comment by iDerp** [comment]
Isn't there a option under the command config that can disable commands being case sensitive? @Emzi0767

**Comment by Emzi0767** [comment]
There is, but it's ignored for subcommands due to oversight.

**Comment by iDerp** [comment]
Ohhhh

**Comment by NaamloosDT** [comment]
Ahh, I knew this issue but forgot to send it to emzi 😂

**Comment by Emzi0767** [comment]
Fixed in latest MyGet build.
